import { Zone, CountryInfo } from './models'

export const availableZones: Zone[] = [
  new Zone('afranet', 'Afranet', 'afra', ['afr']),
  new Zone('asiatech', 'Asiatech', 'asia', [], false),
  new Zone('irancell', 'Irancell', 'ic', []),
];

export const enabledZones = availableZones.filter((z) => z.enabled);
export const enabledZonesMapById = enabledZones.reduce(
  (acc, {name, displayName}) => {
    acc[name] = displayName;
    return acc;
  },
  {}
);
export const enabledZonesMapByIndicator = enabledZones.reduce(
  (acc, {zoneIndicator, displayName}) => {
    acc[zoneIndicator] = displayName;
    return acc;
  },
  {}
);

export const projectEnvironments = {
  test: 'Test',
  staging: 'Staging',
  production: 'Production',
};

export const knownAnnotations = {
  openshiftNodeSelector: 'openshift.io/node-selector',
};

export const knownLabels = {
  projectEnvironment: 'environment',
};

export const knownRouters = {
  Internal: 'Internal',
  Public: 'Public',
  Admin: 'Admin'
};

export const countries: CountryInfo[] = [
  { id: 4, alpha2: 'af', alpha3: 'afg', fa: 'افغانستان', en: 'Afghanistan' },
  { id: 8, alpha2: 'al', alpha3: 'alb', fa: 'آلبانی', en: 'Albania' },
  { id: 12, alpha2: 'dz', alpha3: 'dza', fa: 'الجزایر', en: 'Algeria' },
  { id: 20, alpha2: 'ad', alpha3: 'and', fa: 'آندورا', en: 'Andorra' },
  { id: 24, alpha2: 'ao', alpha3: 'ago', fa: 'آنگولا', en: 'Angola' },
  { id: 28, alpha2: 'ag', alpha3: 'atg', fa: 'آنتیگوا و باربودا', en: 'Antigua and Barbuda' },
  { id: 32, alpha2: 'ar', alpha3: 'arg', fa: 'آرژانتین', en: 'Argentina' },
  { id: 51, alpha2: 'am', alpha3: 'arm', fa: 'ارمنستان', en: 'Armenia' },
  { id: 36, alpha2: 'au', alpha3: 'aus', fa: 'استرالیا', en: 'Australia' },
  { id: 40, alpha2: 'at', alpha3: 'aut', fa: 'اتریش', en: 'Austria' },
  { id: 31, alpha2: 'az', alpha3: 'aze', fa: 'آذربایجان', en: 'Azerbaijan' },
  { id: 44, alpha2: 'bs', alpha3: 'bhs', fa: 'باهاماس', en: 'Bahamas' },
  { id: 48, alpha2: 'bh', alpha3: 'bhr', fa: 'بحرین', en: 'Bahrain' },
  { id: 50, alpha2: 'bd', alpha3: 'bgd', fa: 'بنگلادش', en: 'Bangladesh' },
  { id: 52, alpha2: 'bb', alpha3: 'brb', fa: 'باربادوس', en: 'Barbados' },
  { id: 112, alpha2: 'by', alpha3: 'blr', fa: 'بلاروس', en: 'Belarus' },
  { id: 56, alpha2: 'be', alpha3: 'bel', fa: 'بلژیک', en: 'Belgium' },
  { id: 84, alpha2: 'bz', alpha3: 'blz', fa: 'بلیز', en: 'Belize' },
  { id: 204, alpha2: 'bj', alpha3: 'ben', fa: 'برلین', en: 'Benin' },
  { id: 64, alpha2: 'bt', alpha3: 'btn', fa: 'بوتان', en: 'Bhutan' },
  { id: 68, alpha2: 'bo', alpha3: 'bol', fa: 'بولیوی', en: 'Bolivia (Plurinational State of)' },
  { id: 70, alpha2: 'ba', alpha3: 'bih', fa: 'بوسنی و هرزگوین', en: 'Bosnia and Herzegovina' },
  { id: 72, alpha2: 'bw', alpha3: 'bwa', fa: 'بوتسوانا', en: 'Botswana' },
  { id: 76, alpha2: 'br', alpha3: 'bra', fa: 'برزیل', en: 'Brazil' },
  { id: 96, alpha2: 'bn', alpha3: 'brn', fa: 'برونئی', en: 'Brunei Darussalam' },
  { id: 100, alpha2: 'bg', alpha3: 'bgr', fa: 'بلغارستان', en: 'Bulgaria' },
  { id: 854, alpha2: 'bf', alpha3: 'bfa', fa: 'بورکینافاسو', en: 'Burkina Faso' },
  { id: 108, alpha2: 'bi', alpha3: 'bdi', fa: 'بوروندی', en: 'Burundi' },
  { id: 132, alpha2: 'cv', alpha3: 'cpv', fa: 'کیپ ورد', en: 'Cabo Verde' },
  { id: 116, alpha2: 'kh', alpha3: 'khm', fa: 'کامبوج', en: 'Cambodia' },
  { id: 120, alpha2: 'cm', alpha3: 'cmr', fa: 'کامرون', en: 'Cameroon' },
  { id: 124, alpha2: 'ca', alpha3: 'can', fa: 'کانادا', en: 'Canada' },
  { id: 140, alpha2: 'cf', alpha3: 'caf', fa: 'آفریقای مرکزی', en: 'Central African Republic' },
  { id: 148, alpha2: 'td', alpha3: 'tcd', fa: 'چاد', en: 'Chad' },
  { id: 152, alpha2: 'cl', alpha3: 'chl', fa: 'شیلی', en: 'Chile' },
  { id: 156, alpha2: 'cn', alpha3: 'chn', fa: 'چین', en: 'China' },
  { id: 170, alpha2: 'co', alpha3: 'col', fa: 'کلمبیا', en: 'Colombia' },
  { id: 174, alpha2: 'km', alpha3: 'com', fa: 'کومور', en: 'Comoros' },
  { id: 178, alpha2: 'cg', alpha3: 'cog', fa: 'کنگو', en: 'Congo' },
  {
    id: 180,
    alpha2: 'cd',
    alpha3: 'cod',
    fa: 'جمهوری دموکراتیک کنگو',
    en: 'Congo, Democratic Republic of the',
  },
  { id: 188, alpha2: 'cr', alpha3: 'cri', fa: 'کاستاریکا', en: 'Costa Rica' },
  { id: 384, alpha2: 'ci', alpha3: 'civ', fa: 'ساحل عاج', en: "Côte d'Ivoire" },
  { id: 191, alpha2: 'hr', alpha3: 'hrv', fa: 'کرواسی', en: 'Croatia' },
  { id: 192, alpha2: 'cu', alpha3: 'cub', fa: 'کوبا', en: 'Cuba' },
  { id: 196, alpha2: 'cy', alpha3: 'cyp', fa: 'قبرس', en: 'Cyprus' },
  { id: 203, alpha2: 'cz', alpha3: 'cze', fa: 'چک', en: 'Czechia' },
  { id: 208, alpha2: 'dk', alpha3: 'dnk', fa: 'دانمارک', en: 'Denmark' },
  { id: 262, alpha2: 'dj', alpha3: 'dji', fa: 'جیبوتی', en: 'Djibouti' },
  { id: 212, alpha2: 'dm', alpha3: 'dma', fa: 'دومینیکا', en: 'Dominica' },
  { id: 214, alpha2: 'do', alpha3: 'dom', fa: 'جمهوری دومنیکن', en: 'Dominican Republic' },
  { id: 218, alpha2: 'ec', alpha3: 'ecu', fa: 'اکوادر', en: 'Ecuador' },
  { id: 818, alpha2: 'eg', alpha3: 'egy', fa: 'مصر', en: 'Egypt' },
  { id: 222, alpha2: 'sv', alpha3: 'slv', fa: 'السالوادر', en: 'El Salvador' },
  { id: 226, alpha2: 'gq', alpha3: 'gnq', fa: 'گینه استوایی', en: 'Equatorial Guinea' },
  { id: 232, alpha2: 'er', alpha3: 'eri', fa: 'اریتره', en: 'Eritrea' },
  { id: 233, alpha2: 'ee', alpha3: 'est', fa: 'استونی', en: 'Estonia' },
  { id: 748, alpha2: 'sz', alpha3: 'swz', fa: 'اسواتینی', en: 'Eswatini' },
  { id: 231, alpha2: 'et', alpha3: 'eth', fa: 'اتیوپی', en: 'Ethiopia' },
  { id: 242, alpha2: 'fj', alpha3: 'fji', fa: 'فیجی', en: 'Fiji' },
  { id: 246, alpha2: 'fi', alpha3: 'fin', fa: 'فنلاند', en: 'Finland' },
  { id: 250, alpha2: 'fr', alpha3: 'fra', fa: 'فرانسه', en: 'France' },
  { id: 266, alpha2: 'ga', alpha3: 'gab', fa: 'گابون', en: 'Gabon' },
  { id: 270, alpha2: 'gm', alpha3: 'gmb', fa: 'گامبیا', en: 'Gambia' },
  { id: 268, alpha2: 'ge', alpha3: 'geo', fa: 'گرجستان', en: 'Georgia' },
  { id: 276, alpha2: 'de', alpha3: 'deu', fa: 'آلمان', en: 'Germany' },
  { id: 288, alpha2: 'gh', alpha3: 'gha', fa: 'غنا', en: 'Ghana' },
  { id: 300, alpha2: 'gr', alpha3: 'grc', fa: 'یونان', en: 'Greece' },
  { id: 308, alpha2: 'gd', alpha3: 'grd', fa: 'گرنادا', en: 'Grenada' },
  { id: 320, alpha2: 'gt', alpha3: 'gtm', fa: 'گواتمالا', en: 'Guatemala' },
  { id: 324, alpha2: 'gn', alpha3: 'gin', fa: 'گینه', en: 'Guinea' },
  { id: 624, alpha2: 'gw', alpha3: 'gnb', fa: 'گینه بیسائو', en: 'Guinea-Bissau' },
  { id: 328, alpha2: 'gy', alpha3: 'guy', fa: 'گویان', en: 'Guyana' },
  { id: 332, alpha2: 'ht', alpha3: 'hti', fa: 'هائیتی', en: 'Haiti' },
  { id: 340, alpha2: 'hn', alpha3: 'hnd', fa: 'هندوراس', en: 'Honduras' },
  { id: 348, alpha2: 'hu', alpha3: 'hun', fa: 'مجارستان', en: 'Hungary' },
  { id: 352, alpha2: 'is', alpha3: 'isl', fa: 'ایسلند', en: 'Iceland' },
  { id: 356, alpha2: 'in', alpha3: 'ind', fa: 'هند', en: 'India' },
  { id: 360, alpha2: 'id', alpha3: 'idn', fa: 'اندونزی', en: 'Indonesia' },
  { id: 364, alpha2: 'ir', alpha3: 'irn', fa: 'ایران', en: 'Iran (Islamic Republic of)' },
  { id: 368, alpha2: 'iq', alpha3: 'irq', fa: 'عراق', en: 'Iraq' },
  { id: 372, alpha2: 'ie', alpha3: 'irl', fa: 'ایرلند', en: 'Ireland' },
  //{"id":376,"alpha2":"il","alpha3":"isr",
  //      "fa":"اسرائیل",
  //      "en":"Israel"},
  { id: 380, alpha2: 'it', alpha3: 'ita', fa: 'ایتالیا', en: 'Italy' },
  { id: 388, alpha2: 'jm', alpha3: 'jam', fa: 'جامائیکا', en: 'Jamaica' },
  { id: 392, alpha2: 'jp', alpha3: 'jpn', fa: 'ژاپن', en: 'Japan' },
  { id: 400, alpha2: 'jo', alpha3: 'jor', fa: 'اردن', en: 'Jordan' },
  { id: 398, alpha2: 'kz', alpha3: 'kaz', fa: 'قزاقستان', en: 'Kazakhstan' },
  { id: 404, alpha2: 'ke', alpha3: 'ken', fa: 'کنیا', en: 'Kenya' },
  { id: 296, alpha2: 'ki', alpha3: 'kir', fa: 'چمهوری کیریباتی', en: 'Kiribati' },
  {
    id: 408,
    alpha2: 'kp',
    alpha3: 'prk',
    fa: 'کره شمالی',
    en: "Korea (Democratic People's Republic of)",
  },
  { id: 410, alpha2: 'kr', alpha3: 'kor', fa: 'کره جنوبی', en: 'Korea, Republic of' },
  { id: 414, alpha2: 'kw', alpha3: 'kwt', fa: 'کویت', en: 'Kuwait' },
  { id: 417, alpha2: 'kg', alpha3: 'kgz', fa: 'قرقیزستان', en: 'Kyrgyzstan' },
  { id: 418, alpha2: 'la', alpha3: 'lao', fa: 'لائوس', en: "Lao People's Democratic Republic" },
  { id: 428, alpha2: 'lv', alpha3: 'lva', fa: 'لتونی', en: 'Latvia' },
  { id: 422, alpha2: 'lb', alpha3: 'lbn', fa: 'لبنان', en: 'Lebanon' },
  { id: 426, alpha2: 'ls', alpha3: 'lso', fa: 'لسوتو', en: 'Lesotho' },
  { id: 430, alpha2: 'lr', alpha3: 'lbr', fa: 'لیبریا', en: 'Liberia' },
  { id: 434, alpha2: 'ly', alpha3: 'lby', fa: 'لیبی', en: 'Libya' },
  { id: 438, alpha2: 'li', alpha3: 'lie', fa: 'لیختن اشتاین', en: 'Liechtenstein' },
  { id: 440, alpha2: 'lt', alpha3: 'ltu', fa: 'لیتوانی', en: 'Lithuania' },
  { id: 442, alpha2: 'lu', alpha3: 'lux', fa: 'لوکزامبورگ', en: 'Luxembourg' },
  { id: 450, alpha2: 'mg', alpha3: 'mdg', fa: 'ماداگاسکار', en: 'Madagascar' },
  { id: 454, alpha2: 'mw', alpha3: 'mwi', fa: 'مالاوی', en: 'Malawi' },
  { id: 458, alpha2: 'my', alpha3: 'mys', fa: 'مالزی', en: 'Malaysia' },
  { id: 462, alpha2: 'mv', alpha3: 'mdv', fa: 'مالدیو', en: 'Maldives' },
  { id: 466, alpha2: 'ml', alpha3: 'mli', fa: 'مالی', en: 'Mali' },
  { id: 470, alpha2: 'mt', alpha3: 'mlt', fa: 'مالت', en: 'Malta' },
  { id: 584, alpha2: 'mh', alpha3: 'mhl', fa: 'جزایر مارشال', en: 'Marshall Islands' },
  { id: 478, alpha2: 'mr', alpha3: 'mrt', fa: 'موریتانی', en: 'Mauritania' },
  { id: 480, alpha2: 'mu', alpha3: 'mus', fa: 'موریس', en: 'Mauritius' },
  { id: 484, alpha2: 'mx', alpha3: 'mex', fa: 'مکزیک', en: 'Mexico' },
  {
    id: 583,
    alpha2: 'fm',
    alpha3: 'fsm',
    fa: 'ایالات فدرال میکرونزی',
    en: 'Micronesia (Federated States of)',
  },
  { id: 498, alpha2: 'md', alpha3: 'mda', fa: 'مولداوی', en: 'Moldova, Republic of' },
  { id: 492, alpha2: 'mc', alpha3: 'mco', fa: 'موناکو', en: 'Monaco' },
  { id: 496, alpha2: 'mn', alpha3: 'mng', fa: 'مغولستان', en: 'Mongolia' },
  { id: 499, alpha2: 'me', alpha3: 'mne', fa: 'مونته نگرو', en: 'Montenegro' },
  { id: 504, alpha2: 'ma', alpha3: 'mar', fa: 'مراکش', en: 'Morocco' },
  { id: 508, alpha2: 'mz', alpha3: 'moz', fa: 'موزامبیک', en: 'Mozambique' },
  { id: 104, alpha2: 'mm', alpha3: 'mmr', fa: 'میانمار', en: 'Myanmar' },
  { id: 516, alpha2: 'na', alpha3: 'nam', fa: 'نامیبیا', en: 'Namibia' },
  { id: 520, alpha2: 'nr', alpha3: 'nru', fa: 'نائورو', en: 'Nauru' },
  { id: 524, alpha2: 'np', alpha3: 'npl', fa: 'نپال', en: 'Nepal' },
  { id: 528, alpha2: 'nl', alpha3: 'nld', fa: 'هلند', en: 'Netherlands' },
  { id: 554, alpha2: 'nz', alpha3: 'nzl', fa: 'نیوزیلند', en: 'New Zealand' },
  { id: 558, alpha2: 'ni', alpha3: 'nic', fa: 'نیکاراگوئه', en: 'Nicaragua' },
  { id: 562, alpha2: 'ne', alpha3: 'ner', fa: 'نیجر', en: 'Niger' },
  { id: 566, alpha2: 'ng', alpha3: 'nga', fa: 'نیجریه', en: 'Nigeria' },
  { id: 807, alpha2: 'mk', alpha3: 'mkd', fa: 'مقدونیه شمالی', en: 'North Macedonia' },
  { id: 578, alpha2: 'no', alpha3: 'nor', fa: 'نروژ', en: 'Norway' },
  { id: 512, alpha2: 'om', alpha3: 'omn', fa: 'عمان', en: 'Oman' },
  { id: 586, alpha2: 'pk', alpha3: 'pak', fa: 'پاکستان', en: 'Pakistan' },
  { id: 585, alpha2: 'pw', alpha3: 'plw', fa: 'پالائو', en: 'Palau' },
  { id: 591, alpha2: 'pa', alpha3: 'pan', fa: 'پاناما', en: 'Panama' },
  { id: 598, alpha2: 'pg', alpha3: 'png', fa: 'پاپوآ گینه نو', en: 'Papua New Guinea' },
  { id: 600, alpha2: 'py', alpha3: 'pry', fa: 'پاراگوئه', en: 'Paraguay' },
  { id: 604, alpha2: 'pe', alpha3: 'per', fa: 'پرو', en: 'Peru' },
  { id: 608, alpha2: 'ph', alpha3: 'phl', fa: 'فیلیپین', en: 'Philippines' },
  { id: 616, alpha2: 'pl', alpha3: 'pol', fa: 'لهستان', en: 'Poland' },
  { id: 620, alpha2: 'pt', alpha3: 'prt', fa: 'پرتغال', en: 'Portugal' },
  { id: 634, alpha2: 'qa', alpha3: 'qat', fa: 'قطر', en: 'Qatar' },
  { id: 642, alpha2: 'ro', alpha3: 'rou', fa: 'رومانی', en: 'Romania' },
  { id: 643, alpha2: 'ru', alpha3: 'rus', fa: 'روسیه', en: 'Russian Federation' },
  { id: 646, alpha2: 'rw', alpha3: 'rwa', fa: 'رواندا', en: 'Rwanda' },
  { id: 659, alpha2: 'kn', alpha3: 'kna', fa: 'سنت کیتس و نویس', en: 'Saint Kitts and Nevis' },
  { id: 662, alpha2: 'lc', alpha3: 'lca', fa: 'سنت لوسیا', en: 'Saint Lucia' },
  {
    id: 670,
    alpha2: 'vc',
    alpha3: 'vct',
    fa: 'سنت وینسنت و گرنادین ها',
    en: 'Saint Vincent and the Grenadines',
  },
  { id: 882, alpha2: 'ws', alpha3: 'wsm', fa: 'ساموآ', en: 'Samoa' },
  { id: 674, alpha2: 'sm', alpha3: 'smr', fa: 'سان مارینو', en: 'San Marino' },
  { id: 678, alpha2: 'st', alpha3: 'stp', fa: 'سائوتومه و پرنسیپ', en: 'Sao Tome and Principe' },
  { id: 682, alpha2: 'sa', alpha3: 'sau', fa: 'عربستان سعودی', en: 'Saudi Arabia' },
  { id: 686, alpha2: 'sn', alpha3: 'sen', fa: 'سنگال', en: 'Senegal' },
  { id: 688, alpha2: 'rs', alpha3: 'srb', fa: 'صربستان', en: 'Serbia' },
  { id: 690, alpha2: 'sc', alpha3: 'syc', fa: 'سیشل', en: 'Seychelles' },
  { id: 694, alpha2: 'sl', alpha3: 'sle', fa: 'سیرالئون', en: 'Sierra Leone' },
  { id: 702, alpha2: 'sg', alpha3: 'sgp', fa: 'سنگاپور', en: 'Singapore' },
  { id: 703, alpha2: 'sk', alpha3: 'svk', fa: 'اسلواکی', en: 'Slovakia' },
  { id: 705, alpha2: 'si', alpha3: 'svn', fa: 'اسلوونی', en: 'Slovenia' },
  { id: 90, alpha2: 'sb', alpha3: 'slb', fa: 'جزایر سلیمان', en: 'Solomon Islands' },
  { id: 706, alpha2: 'so', alpha3: 'som', fa: 'سومالی', en: 'Somalia' },
  { id: 710, alpha2: 'za', alpha3: 'zaf', fa: 'آفریقای جنوبی', en: 'South Africa' },
  { id: 728, alpha2: 'ss', alpha3: 'ssd', fa: 'سودان جنوبی', en: 'South Sudan' },
  { id: 724, alpha2: 'es', alpha3: 'esp', fa: 'اسپانیا', en: 'Spain' },
  { id: 144, alpha2: 'lk', alpha3: 'lka', fa: 'سری لانکا', en: 'Sri Lanka' },
  { id: 729, alpha2: 'sd', alpha3: 'sdn', fa: 'سودان', en: 'Sudan' },
  { id: 740, alpha2: 'sr', alpha3: 'sur', fa: 'سورینام', en: 'Suriname' },
  { id: 752, alpha2: 'se', alpha3: 'swe', fa: 'سوئد', en: 'Sweden' },
  { id: 756, alpha2: 'ch', alpha3: 'che', fa: 'سوئیس', en: 'Switzerland' },
  { id: 760, alpha2: 'sy', alpha3: 'syr', fa: 'سوریه', en: 'Syrian Arab Republic' },
  { id: 762, alpha2: 'tj', alpha3: 'tjk', fa: 'تاجیکستان', en: 'Tajikistan' },
  { id: 834, alpha2: 'tz', alpha3: 'tza', fa: 'تانزانیا', en: 'Tanzania, United Republic of' },
  { id: 764, alpha2: 'th', alpha3: 'tha', fa: 'تایلند', en: 'Thailand' },
  { id: 626, alpha2: 'tl', alpha3: 'tls', fa: 'تیمور شرقی', en: 'Timor-Leste' },
  { id: 768, alpha2: 'tg', alpha3: 'tgo', fa: 'توگو', en: 'Togo' },
  { id: 776, alpha2: 'to', alpha3: 'ton', fa: 'تونگا', en: 'Tonga' },
  { id: 780, alpha2: 'tt', alpha3: 'tto', fa: 'ترینیداد و توباگو', en: 'Trinidad and Tobago' },
  { id: 788, alpha2: 'tn', alpha3: 'tun', fa: 'تونس', en: 'Tunisia' },
  { id: 792, alpha2: 'tr', alpha3: 'tur', fa: 'ترکیه', en: 'Turkey' },
  { id: 795, alpha2: 'tm', alpha3: 'tkm', fa: 'ترکمنستان', en: 'Turkmenistan' },
  { id: 798, alpha2: 'tv', alpha3: 'tuv', fa: 'تووالو', en: 'Tuvalu' },
  { id: 800, alpha2: 'ug', alpha3: 'uga', fa: 'اوگاندا', en: 'Uganda' },
  { id: 804, alpha2: 'ua', alpha3: 'ukr', fa: 'اوکراین', en: 'Ukraine' },
  { id: 784, alpha2: 'ae', alpha3: 'are', fa: 'امارات متحده عربی', en: 'United Arab Emirates' },
  {
    id: 826,
    alpha2: 'gb',
    alpha3: 'gbr',
    fa: 'بریتانیا',
    en: 'United Kingdom of Great Britain and Northern Ireland',
  },
  {
    id: 840,
    alpha2: 'us',
    alpha3: 'usa',
    fa: 'ایالات متحده آمریکا',
    en: 'United States of America',
  },
  { id: 858, alpha2: 'uy', alpha3: 'ury', fa: 'اروگوئه', en: 'Uruguay' },
  { id: 860, alpha2: 'uz', alpha3: 'uzb', fa: 'ازبکستان', en: 'Uzbekistan' },
  { id: 548, alpha2: 'vu', alpha3: 'vut', fa: 'وانواتو', en: 'Vanuatu' },
  { id: 862, alpha2: 've', alpha3: 'ven', fa: 'ونزوئلا', en: 'Venezuela (Bolivarian Republic of)' },
  { id: 704, alpha2: 'vn', alpha3: 'vnm', fa: 'ویتنام', en: 'Viet Nam' },
  { id: 887, alpha2: 'ye', alpha3: 'yem', fa: 'یمن', en: 'Yemen' },
  { id: 894, alpha2: 'zm', alpha3: 'zmb', fa: 'زامبیا', en: 'Zambia' },
  { id: 716, alpha2: 'zw', alpha3: 'zwe', fa: 'زیمبابوه', en: 'Zimbabwe' },
];

export function createView(countries: CountryInfo[]) {
  return countries.reduce(
    (acc, {alpha2, en, fa}) => {
      acc[alpha2] = `${en}/${fa}`;
      return acc;
    },
    {}
  )
}

export const countriesMap = createView(countries);
export const fiterCountries = (text: string) => {
  return createView(countries.filter((cty: CountryInfo) => cty.en.indexOf(text) != -1));
};
